### REGISTER ADMIN
POST http://localhost:5000/register/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0ZTc2NGIwZWIyMWUwYjk5NTI3YjkxYyIsInJvbGUiOiJzdXBlcl9hZG1pbiJ9LCJpYXQiOjE2OTMwNTQyNTQsImV4cCI6MTY5MzE0MDY1NH0.Zope1NVgsslRWtl6xWSFrtSeDf4gqOubL-9X7LYo-l8
Content-Type: application/json

{
  "first_name": "Hamkor",
  "last_name": "Bank",
  "image": "logohamkor.jpg",
  "username": "hamkor.bank",
  "password": "1234"
}


### Login ADMIN
POST http://localhost:5000/login/admin
Content-Type: application/json

{
  "username": "sherozbek.17",
  "password": "1234"
}

### List Admin
GET http://localhost:5000/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0ZTc2NGIwZWIyMWUwYjk5NTI3YjkxYyIsInJvbGUiOiJzdXBlcl9hZG1pbiJ9LCJpYXQiOjE2OTMwNTQyNTQsImV4cCI6MTY5MzE0MDY1NH0.Zope1NVgsslRWtl6xWSFrtSeDf4gqOubL-9X7LYo-l8


### Show Admin
GET http://localhost:5000/admin/64e99e98bf3f2768d5517009
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0ZTc2NGIwZWIyMWUwYjk5NTI3YjkxYyIsInJvbGUiOiJzdXBlcl9hZG1pbiJ9LCJpYXQiOjE2OTMwNTQyNTQsImV4cCI6MTY5MzE0MDY1NH0.Zope1NVgsslRWtl6xWSFrtSeDf4gqOubL-9X7LYo-l8

### Delete Admin
DELETE http://localhost:5000/admin/64e99e98bf3f2768d5517009
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0ZTc2NGIwZWIyMWUwYjk5NTI3YjkxYyIsInJvbGUiOiJzdXBlcl9hZG1pbiJ9LCJpYXQiOjE2OTMwNTQyNTQsImV4cCI6MTY5MzE0MDY1NH0.Zope1NVgsslRWtl6xWSFrtSeDf4gqOubL-9X7LYo-l8

### UnDelete Admin
DELETE http://localhost:5000/admin/un/64e99e98bf3f2768d5517009
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0ZTc2NGIwZWIyMWUwYjk5NTI3YjkxYyIsInJvbGUiOiJzdXBlcl9hZG1pbiJ9LCJpYXQiOjE2OTMwNTQyNTQsImV4cCI6MTY5MzE0MDY1NH0.Zope1NVgsslRWtl6xWSFrtSeDf4gqOubL-9X7LYo-l8
