### REGISTER ADMIN
POST http://localhost:5000/register/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUwMWQ0MzVhOGM5NzI2NGJkMmU0MTUzIiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDYxODczNCwiZXhwIjoxNjk0NzA1MTM0fQ.QMtydDeQugU4Yk60SchanmxEWTQTbtXCnPSbW9W2V88
Content-Type: application/json

{
  "first_name": "dfsgdfg",
  "last_name": "Bank",
  "image": "logohamkor.jpg",
  "username": "sherozbekwdfdf.17",
  "password": "123dgf4"
}


### Login ADMIN
POST http://localhost:5000/login/admin
Content-Type: application/json

{
  "username": "ayubxon",
  "password": "12345678"
}

### List Admin
GET http://localhost:5000/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlYjZjNGY1ZGQxN2E5YzZkNTJiNGM3Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDYxMzU0NCwiZXhwIjoxNjk0Njk5OTQ0fQ.LCCUE77_zBeI39DKSaotkNlJyMNWEi2RjVta5D87XoY


### Show Admin
GET http://localhost:5000/admin/64e99e98bf3f2768d5517009
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlYjZjNGY1ZGQxN2E5YzZkNTJiNGM3Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDYxMzU0NCwiZXhwIjoxNjk0Njk5OTQ0fQ.LCCUE77_zBeI39DKSaotkNlJyMNWEi2RjVta5D87XoY

### Delete Admin
DELETE http://localhost:5000/admin/64e99e98bf3f2768d5517009
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlYjZjNGY1ZGQxN2E5YzZkNTJiNGM3Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDYxMzU0NCwiZXhwIjoxNjk0Njk5OTQ0fQ.LCCUE77_zBeI39DKSaotkNlJyMNWEi2RjVta5D87XoY

### UnDelete Admin
DELETE http://localhost:5000/admin/un/64e99e98bf3f2768d5517009
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlYjZjNGY1ZGQxN2E5YzZkNTJiNGM3Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDYxMzU0NCwiZXhwIjoxNjk0Njk5OTQ0fQ.LCCUE77_zBeI39DKSaotkNlJyMNWEi2RjVta5D87XoY



### EDIT ADMIN
PATCH  http://localhost:5000/admin/64eb6c4f5dd17a9c6d52b4cb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlYjZjNGY1ZGQxN2E5YzZkNTJiNGM3Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDYxMzU0NCwiZXhwIjoxNjk0Njk5OTQ0fQ.LCCUE77_zBeI39DKSaotkNlJyMNWEi2RjVta5D87XoY
Content-Type: application/json

{
  "first_name": "Asadbek",
  "last_name": "Mansurov",
  "image": "logohamkor.jpg",
  "username": "asadbekjon"
}



### Change Password
PATCH  http://localhost:5000/change/password/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlYjZjNGY1ZGQxN2E5YzZkNTJiNGM3Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDYxMzU0NCwiZXhwIjoxNjk0Njk5OTQ0fQ.LCCUE77_zBeI39DKSaotkNlJyMNWEi2RjVta5D87XoY
Content-Type: application/json

{
  "current_password": "1234156",
  "new_password": "123456"
}