### POST MARKET CATEGORY
POST http://localhost:5000/market-category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlYjZjNGY1ZGQxN2E5YzZkNTJiNGM3Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDY2OTU4MiwiZXhwIjoxNjk0NzU1OTgyfQ.XBqWmlPp535RmcsbKMt3HYLuYEqIbgYsmBSvSA4OKlY

{
  "name":"Kiyimlar"
}