### SELLER REGISTER
POST http://localhost:5000/register/seller
Content-Type: application/json

{
  "first_name": "Person",
  "last_name": "Jeckson",
  "email": "person111@gmail.com",
  "address": "Toshkent Chilonzor",
  "phone_number": "+998958657506",
  "username": "personbek",
  "password": "123456"
}

### SELLER LOGIN
POST http://localhost:5000/login/seller
Content-Type: application/json

{
  "username": "personbek",
  "password": "123456"
}


### Change Allow Seller
POST http://localhost:5000/change/allow/seller/65019aba522ecaf22b10e144
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlYjZjNGY1ZGQxN2E5YzZkNTJiNGM3Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDYxNjY2NSwiZXhwIjoxNjk0NzAzMDY1fQ.MR9NXNLUdJmVRORqFyc3tMjLopaxU9S1CcKak5kjT2I
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUwMTlhYmE1MjJlY2FmMjJiMTBlMTQ0Iiwicm9sZSI6InNlbGxlciJ9LCJpYXQiOjE2OTQ2MTcyNjcsImV4cCI6MTY5NDcwMzY2N30.cUs5OkV3_KcxAsJM8nuhDO-uo4AMDqgCb3DvLDFzzrQ



### Remove Seller by Admin
DELETE http://localhost:5000/seller/65019aba522ecaf22b10e144
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlYjZjNGY1ZGQxN2E5YzZkNTJiNGM3Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5NDYxNjY2NSwiZXhwIjoxNjk0NzAzMDY1fQ.MR9NXNLUdJmVRORqFyc3tMjLopaxU9S1CcKak5kjT2I
