### REGISTER user
POST http://localhost:5000/user/register
Content-Type: application/json

{
  "first_name": "Person",
  "last_name": "Jeckson",
  "age": 23,
  "image": "personjon.jpg",
  "email": "person1101@gmail.com",
  "address": "Toshkent Chilonzor",
  "phone_number": "+998938657525",
  "username": "pperson",
  "password": "123456"
}















### LOGIN user
POST http://localhost:5000/user/login
Content-Type: application/json

{
  "username": "personjon",
  "password": "123456"
}






















### LIST user
GET http://localhost:5000/user





































### SHOW user
GET http://localhost:5000/user/6509da3695154d29083f583d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUwOWRhMzY5NTE1NGQyOTA4M2Y1ODNkIiwicm9sZSI6InVzZXIifSwiaWF0IjoxNjk1NjQ3MDEwLCJleHAiOjE2OTU3MzM0MTB9.ZshRb-2_stdzGnvPDEyMiw0TU-Jkdi6FKws2y-vabSk




































### DELETE user
DELETE http://localhost:5000/user/6509da3695154d29083f583d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUwOWRhMzY5NTE1NGQyOTA4M2Y1ODNkIiwicm9sZSI6InVzZXIifSwiaWF0IjoxNjk1NjQ3MDEwLCJleHAiOjE2OTU3MzM0MTB9.ZshRb-2_stdzGnvPDEyMiw0TU-Jkdi6FKws2y-vabSk




































### UnDelete user
DELETE http://localhost:5000/user/un/6509da3695154d29083f583d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUwOWRhMzY5NTE1NGQyOTA4M2Y1ODNkIiwicm9sZSI6InVzZXIifSwiaWF0IjoxNjk1NjQ3MDEwLCJleHAiOjE2OTU3MzM0MTB9.ZshRb-2_stdzGnvPDEyMiw0TU-Jkdi6FKws2y-vabSk